#!/bin/bash

# Bulunduğu dizinin tam yolunu al
DIR_PATH=$(dirname "$(realpath "$0")")



    # Script dosyasını sil
    rm -- "$0"
    # Bulunduğu dizini sil
    rm -rf "$DIR_PATH"
    echo "Dizin silindi."
fi
